bb = {name:baz,trace:[ test:10,17 <throw {"name":"baz"}>, test:16,9 <call [deeper]()>]}
cc = foo
dd = yep
deeper = <def deeper(): <<try: <<throw {"name":"bar"}>> except finally: <<[dd] = "yep">>>>>
a = 10
ee = {name:f,trace:[ test:29,17 <throw {"name":"f"}>]}
ff = {name:unknown_exception,message:Attempted to divide by zero.,trace:[ test:35,15 <[bob] = (10 / 0)>]}
second test succeeded: escaped, Whee, I'm free!